dist: bionic
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - sudo wget -O- http://neuro.debian.net/lists/bionic.us-ca.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver pool.sks-keyservers.net 2649A5A9 || { sudo wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -; }
  - sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install -y singularity-container
  - sudo apt-get install build-essential libblas-dev liblapack-dev python3-tk

stage: Tests
script:
  - python setup.py develop
  - export MPLBACKEND="agg"
  - pytest -v


jobs:
  include:
    - stage: Deploy Docker latest
      if: branch = master AND type = push
      script:
        - travis_wait 60 docker build -t docker-scilpy containers
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag docker-scilpy $DOCKER_USERNAME/docker-scilpy:latest
        - travis_wait 60 docker push $DOCKER_USERNAME/docker-scilpy:latest
    - stage: Deploy Docker release
      if: tag IS present
      script:
        - travis_wait 60 docker build -t docker-scilpy containers
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag docker-scilpy $DOCKER_USERNAME/docker-scilpy:$TRAVIS_TAG
        - travis_wait 60 docker push $DOCKER_USERNAME/docker-scilpy:$TRAVIS_TAG
    - stage: Deploy Singularity release
      if: tag IS present
      script:
        - travis_wait 60 sudo singularity build singularity_scilpy_${TRAVIS_TAG}.img containers/singularity_scilpy.def
        - singularity exec singularity_scilpy_${TRAVIS_TAG}.img echo "Singularity test"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: singularity_scilpy_${TRAVIS_TAG}.img
        skip_cleanup: true
        on:
          tags: true

